DROP FUNCTION IF EXISTS addgeometrycolumn(character varying, character varying, integer, character varying, integer);
DROP FUNCTION IF EXISTS addgeometrycolumn(character varying, character varying, character varying, integer, character varying, integer);
DROP FUNCTION IF EXISTS addgeometrycolumn(character varying, character varying, character varying, character varying, integer, character varying, integer);
DROP FUNCTION IF EXISTS affine(geometry, double precision, double precision, double precision, double precision, double precision, double precision);
DROP FUNCTION IF EXISTS asgml(geometry);
DROP FUNCTION IF EXISTS asgml(geometry, integer);
DROP FUNCTION IF EXISTS askml(geometry, integer);
DROP FUNCTION IF EXISTS askml(geometry);
DROP FUNCTION IF EXISTS askml(integer, geometry, integer);
DROP FUNCTION IF EXISTS bdmpolyfromtext(text, integer);
DROP FUNCTION IF EXISTS bdpolyfromtext(text, integer);
DROP FUNCTION IF EXISTS buffer(geometry, double precision, integer);
DROP FUNCTION IF EXISTS count_em_all();
DROP FUNCTION IF EXISTS find_extent(text, text, text);
DROP FUNCTION IF EXISTS find_extent(text, text);
DROP FUNCTION IF EXISTS fix_geometry_columns();
DROP FUNCTION IF EXISTS geomcollfromtext(text, integer);
DROP FUNCTION IF EXISTS geomcollfromtext(text);
DROP FUNCTION IF EXISTS geomcollfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS geomcollfromwkb(bytea);
DROP FUNCTION IF EXISTS geomfromtext(text);
DROP FUNCTION IF EXISTS geomfromtext(text, integer);
DROP FUNCTION IF EXISTS geomfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS linefromtext(text);
DROP FUNCTION IF EXISTS linefromtext(text, integer);
DROP FUNCTION IF EXISTS linefromwkb(bytea);
DROP FUNCTION IF EXISTS linefromwkb(bytea, integer);
DROP FUNCTION IF EXISTS linestringfromtext(text);
DROP FUNCTION IF EXISTS linestringfromtext(text, integer);
DROP FUNCTION IF EXISTS linestringfromwkb(bytea);
DROP FUNCTION IF EXISTS linestringfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS locate_along_measure(geometry, double precision);
DROP FUNCTION IF EXISTS mlinefromtext(text);
DROP FUNCTION IF EXISTS mlinefromtext(text, integer);
DROP FUNCTION IF EXISTS mlinefromwkb(bytea, integer);
DROP FUNCTION IF EXISTS mlinefromwkb(bytea);
DROP FUNCTION IF EXISTS mpointfromtext(text);
DROP FUNCTION IF EXISTS mpointfromtext(text, integer);
DROP FUNCTION IF EXISTS mpointfromwkb(bytea);
DROP FUNCTION IF EXISTS mpointfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS mpolyfromtext(text);
DROP FUNCTION IF EXISTS mpolyfromtext(text, integer);
DROP FUNCTION IF EXISTS mpolyfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS mpolyfromwkb(bytea);
DROP FUNCTION IF EXISTS multilinefromwkb(bytea, integer);
DROP FUNCTION IF EXISTS multilinefromwkb(bytea);
DROP FUNCTION IF EXISTS multilinestringfromtext(text, integer);
DROP FUNCTION IF EXISTS multilinestringfromtext(text);
DROP FUNCTION IF EXISTS multipointfromtext(text);
DROP FUNCTION IF EXISTS multipointfromtext(text, integer);
DROP FUNCTION IF EXISTS multipointfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS multipointfromwkb(bytea);
DROP FUNCTION IF EXISTS multipolyfromwkb(bytea);
DROP FUNCTION IF EXISTS multipolyfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS multipolygonfromtext(text, integer);
DROP FUNCTION IF EXISTS multipolygonfromtext(text);
DROP FUNCTION IF EXISTS pointfromtext(text, integer);
DROP FUNCTION IF EXISTS pointfromtext(text);
DROP FUNCTION IF EXISTS pointfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS pointfromwkb(bytea);
DROP FUNCTION IF EXISTS polyfromtext(text);
DROP FUNCTION IF EXISTS polyfromtext(text, integer);
DROP FUNCTION IF EXISTS polyfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS polyfromwkb(bytea);
DROP FUNCTION IF EXISTS polygonfromtext(text, integer);
DROP FUNCTION IF EXISTS polygonfromtext(text);
DROP FUNCTION IF EXISTS polygonfromwkb(bytea, integer);
DROP FUNCTION IF EXISTS polygonfromwkb(bytea);
DROP FUNCTION IF EXISTS populate_geometry_columns(oid);
DROP FUNCTION IF EXISTS populate_geometry_columns();
DROP FUNCTION IF EXISTS probe_geometry_columns();
DROP FUNCTION IF EXISTS rename_geometry_table_constraints();
DROP FUNCTION IF EXISTS rotate(geometry, double precision);
DROP FUNCTION IF EXISTS rotatex(geometry, double precision);
DROP FUNCTION IF EXISTS rotatey(geometry, double precision);
DROP FUNCTION IF EXISTS rotatez(geometry, double precision);
DROP FUNCTION IF EXISTS scale(geometry, double precision, double precision, double precision);
DROP FUNCTION IF EXISTS scale(geometry, double precision, double precision);
DROP FUNCTION IF EXISTS se_envelopesintersect(geometry, geometry);
DROP FUNCTION IF EXISTS se_locatealong(geometry, double precision);
DROP FUNCTION IF EXISTS snaptogrid(geometry, double precision, double precision);
DROP FUNCTION IF EXISTS snaptogrid(geometry, double precision);
DROP FUNCTION IF EXISTS st_area(geography);
DROP FUNCTION IF EXISTS st_asbinary(text);
DROP FUNCTION IF EXISTS st_asgeojson(geography);
DROP FUNCTION IF EXISTS st_asgeojson(geometry);
DROP FUNCTION IF EXISTS st_asgeojson(integer, geography);
DROP FUNCTION IF EXISTS st_asgeojson(integer, geometry);
DROP FUNCTION IF EXISTS st_asgeojson(geography, integer);
DROP FUNCTION IF EXISTS st_asgeojson(geometry, integer);
DROP FUNCTION IF EXISTS st_asgeojson(integer, geography, integer);
DROP FUNCTION IF EXISTS st_asgeojson(integer, geometry, integer);
DROP FUNCTION IF EXISTS st_asgml(geography);
DROP FUNCTION IF EXISTS st_asgml(geometry);
DROP FUNCTION IF EXISTS st_asgml(integer, geography);
DROP FUNCTION IF EXISTS st_asgml(integer, geometry);
DROP FUNCTION IF EXISTS st_asgml(geometry, integer);
DROP FUNCTION IF EXISTS st_asgml(integer, geography, integer);
DROP FUNCTION IF EXISTS st_asgml(integer, geometry, integer);
DROP FUNCTION IF EXISTS st_asgml(integer, geography, integer, integer);
DROP FUNCTION IF EXISTS st_asgml(integer, geometry, integer, integer);
DROP FUNCTION IF EXISTS st_asgml(geography, integer);
DROP FUNCTION IF EXISTS st_askml(geography);
DROP FUNCTION IF EXISTS st_askml(geometry);
DROP FUNCTION IF EXISTS st_askml(integer, geometry);
DROP FUNCTION IF EXISTS st_askml(integer, geography, integer);
DROP FUNCTION IF EXISTS st_askml(integer, geometry, integer);
DROP FUNCTION IF EXISTS st_askml(integer, geography);
DROP FUNCTION IF EXISTS st_geohash(geometry);
DROP FUNCTION IF EXISTS st_length(geography);
DROP FUNCTION IF EXISTS st_minimumboundingcircle(geometry);
DROP FUNCTION IF EXISTS translate(geometry, double precision, double precision, double precision);
DROP FUNCTION IF EXISTS translate(geometry, double precision, double precision);
DROP FUNCTION IF EXISTS transscale(geometry, double precision, double precision, double precision, double precision);